//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeMachine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoffeeMachine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;machine&quot;: {
        ///    &quot;outlets&quot;: {
        ///      &quot;count_n&quot;: 3
        ///    },
        ///    &quot;total_items_quantity&quot;: {
        ///      &quot;hot_water&quot;: 500,
        ///      &quot;hot_milk&quot;: 500,
        ///      &quot;ginger_syrup&quot;: 100,
        ///      &quot;sugar_syrup&quot;: 100,
        ///      &quot;tea_leaves_syrup&quot;: 100
        ///    },
        ///    &quot;beverages&quot;: {
        ///      &quot;hot_tea&quot;: {
        ///        &quot;hot_water&quot;: 200,
        ///        &quot;hot_milk&quot;: 100,
        ///        &quot;ginger_syrup&quot;: 10,
        ///        &quot;sugar_syrup&quot;: 10,
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///      &quot;hot_coffee&quot;: {
        ///        &quot;hot_water&quot;: 100,
        ///        &quot;ginger_syrup&quot;: 30,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string case1 {
            get {
                return ResourceManager.GetString("case1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;machine&quot;: {
        ///  }
        ///}.
        /// </summary>
        internal static string case2 {
            get {
                return ResourceManager.GetString("case2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;machine&quot;: {
        ///    &quot;outlets&quot;: {
        ///      &quot;count_n&quot;: 3
        ///    },
        ///    &quot;total_items_quantity&quot;: {
        ///      &quot;hot_water&quot;: 500,
        ///      &quot;hot_milk&quot;: 500,
        ///    },
        ///    &quot;beverages&quot;: {
        ///      &quot;hot_tea&quot;: {
        ///        &quot;ginger_syrup&quot;: 10,
        ///        &quot;sugar_syrup&quot;: 10,
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///      &quot;hot_coffee&quot;: {
        ///        &quot;hot_milk&quot;: 400,
        ///      },
        ///      &quot;black_tea&quot;: {
        ///      },
        ///      &quot;green_tea&quot;: {
        ///        &quot;hot_water&quot;: 100,
        ///      },
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string case3 {
            get {
                return ResourceManager.GetString("case3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;machine&quot;: {
        ///    &quot;outlets&quot;: {
        ///      &quot;count_n&quot;: 6
        ///    },
        ///    &quot;total_items_quantity&quot;: {
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///    },
        ///    &quot;beverages&quot;: {
        ///      &quot;hot_tea&quot;: {
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///      &quot;hot_coffee&quot;: {
        ///       &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///      &quot;black_tea&quot;: {
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///      &quot;green_tea&quot;: {
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string case4 {
            get {
                return ResourceManager.GetString("case4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;machine&quot;: {
        ///    &quot;outlets&quot;: {
        ///      &quot;count_n&quot;: 66666
        ///    },
        ///    &quot;total_items_quantity&quot;: {
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///    },
        ///    &quot;beverages&quot;: {
        ///      &quot;hot_tea&quot;: {
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///      &quot;hot_coffee&quot;: {
        ///       &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///      &quot;black_tea&quot;: {
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///      &quot;green_tea&quot;: {
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string case5 {
            get {
                return ResourceManager.GetString("case5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;machine&quot;: {
        ///    &quot;outlets&quot;: {
        ///      &quot;count_n&quot;: 345678
        ///    },
        ///    &quot;total_items_quantity&quot;: {
        ///      &quot;hot_water&quot;: 234567,
        ///      &quot;hot_milk&quot;: 500,
        ///      &quot;ginger_syrup&quot;: 45678,
        ///      &quot;sugar_syrup&quot;: 100,
        ///      &quot;tea_leaves_syrup&quot;: 100
        ///    },
        ///    &quot;beverages&quot;: {
        ///      &quot;hot_tea&quot;: {
        ///        &quot;hot_water&quot;: 200,
        ///        &quot;hot_milk&quot;: 100,
        ///        &quot;ginger_syrup&quot;: 10,
        ///        &quot;sugar_syrup&quot;: 10,
        ///        &quot;tea_leaves_syrup&quot;: 30
        ///      },
        ///      &quot;hot_coffee&quot;: {
        ///        &quot;hot_water&quot;: 100,
        ///        &quot;ginger_syrup [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string case6 {
            get {
                return ResourceManager.GetString("case6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;machine&quot;: {
        ///    &quot;outlets&quot;: {
        ///      &quot;count_n&quot;: 2
        ///    },
        ///    &quot;total_items_quantity&quot;: {
        ///      &quot;hot_water&quot;: 1000,
        ///        &quot;hot_milk&quot;: 200,
        ///        &quot;ginger_syrup&quot;: 1000,
        ///    },
        ///    &quot;beverages&quot;: {
        ///      &quot;hot_tea&quot;: {
        ///       &quot;hot_water&quot;: 200,
        ///        &quot;hot_milk&quot;: 100,
        ///        &quot;ginger_syrup&quot;: 10,
        ///      },
        ///      &quot;hot_coffee&quot;: {
        ///        &quot;hot_water&quot;: 200,
        ///        &quot;hot_milk&quot;: 100,
        ///        &quot;ginger_syrup&quot;: 10,
        ///      },
        ///      &quot;black_tea&quot;: {
        ///        &quot;hot_water&quot;: 200,
        ///        &quot;hot_milk&quot;: 100,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string case7 {
            get {
                return ResourceManager.GetString("case7", resourceCulture);
            }
        }
    }
}
